### ISSUE TITLE
You asked me to contact you here?

### ISSUE THREAD

**Issue by vutondesign** [redmangospros/redmangospros.github.io#2]

**Comment by redmangospros** [comment]
JUst Got here before the cc

**Comment by redmangospros** [comment]
Talk to me on discord

**Comment by redmangospros** [comment]
https://discord.gg/sSDRXdP

**Comment by vutondesign** [comment]
I don't use discord

**Comment by redmangospros** [comment]
you do, you made a youtube video

**Comment by vutondesign** [comment]
That was an account made for the purpose of tutorials, and I don't even have a youtube channel anymore.

**Comment by redmangospros** [comment]
what happend to it?

**Comment by redmangospros** [comment]
lets make something together? you chosse?

**Comment by vutondesign** [comment]
I don't have time to mess about with random projects, I'll only work with someone if they have an idea that I think will work.

**Comment by redmangospros** [comment]
like what, lets work on a big chrom extestion. some app for scratchers etc

**Comment by vutondesign** [comment]
I would need an exact description of this "big chrom extestion".

**Comment by redmangospros** [comment]
A Extesttion to help people with their needs like weather,time,traffic, and etc.

**Comment by redmangospros** [comment]
using a api and news

**Comment by vutondesign** [comment]
That's not really an idea

**Comment by redmangospros** [comment]
that is. plz?

**Comment by vutondesign** [comment]
I need:

The extension name:
What it'll so (exactly):
Will it be in the store?:
What will the site look like?:
What will be done to get extension attention, ads for them are mostly banned on scratch:
When will It be done:
We clearly live in different timezones, how would we work that?:
What is the extension tagline?:
Logo ideas?:
Langauge?:

**Comment by redmangospros** [comment]
The extension name: will do later
What it'll do (exactly): 

A Extesttion to help people with their needs like weather,time,traffic, and etc.
--



Will it be in the store?: maybe
What will the site look like?: 
What will be done to get extension attention, ads for them are mostly banned on scratch: advertise on github or raise about it on our webistes, + you have a lot of follwers.
When will It be done: next year
We clearly live in different timezones, how would we work that?: what timezone are you? We will add difffernt settings to find loaction and timezone.
What is the extension tagline?: tagline?
Logo ideas?: Yo decide.
Langauge?: English

**Comment by vutondesign** [comment]
> Langauge?: English

I meant programming language 

> What is the extension tagline?: tagline?

Basically a slogan

> When will It be done: next year

wow

> We clearly live in different timezones, how would we work that?: what timezone are you? We will add difffernt settings to find loaction and timezone.

I meant getting work done 

> A Extesttion to help people with their needs like weather,time,traffic, and etc.

I'm sure there are many of these about

**Comment by vutondesign** [comment]
I've decided not to take up your offer, mostly because you don't seem to know much about extensions.

**Comment by redmangospros** [comment]
no, plz. keep one more chance!

**Comment by redmangospros** [comment]
js
imangine checking your phone, tv and tablet for traffic and etc, well it just got better
well, we will figyre out like  you do half the time, i do rest
well we will make it way better

**Comment by redmangospros** [comment]
Plz?

**Comment by vutondesign** [comment]
Sorry, no

**Comment by redmangospros** [comment]
i will advertise you
